### PR TITLE
Some small fixes

### PR DESCRIPTION
**Pull request by rafaelrojasmiliani**
I'm using the amazing tool in a personal project and I implement some fixes I needed. 
The fixes are
- Add static keyword on member functions
- Fix static keyword string
- Fix inheritance string.
- Close file where c++ code is written in the destruct of the cpp code generator (pease, check if this is ok)

### CODE REVIEW

**Comment by rafaelrojasmiliani** [comment]
I would like to add also the possibility of adding custom types to classes, like `using`/ `typedef`. What would be the best methodology?

**Comment by yuchdev** [comment]
Thank you for your contribution!
Is it okay if I ask you to add a small unit test?
The project suffers from a lack of meaningful test cases.

You can add `class CppUsing`, e.g.
`CppUsing(name='vec', value='std::vector<int, alloc<int>>')`
which can be rendered as 
`using vec = std::vector<int, Alloc<int>>;`

In the class declaration it can be rendered between enums and nested classes.

**Comment by yuchdev** [comment]
@rafaelrojasmiliani If you don't have time for tests now it's fine of course
Just tell me, I will accept your PR anyway

**Comment by rafaelrojasmiliani** [comment]
I Added a small test on the file creation. But I don't have an idea of how to test for a code generation.

**Comment by yuchdev** [comment]
@rafaelrojasmiliani 
You can take a look at existing tests

Creating C++ file:
https://github.com/yuchdev/code_generator/blob/master/tests/test_cpp_file.py

Creating in-memory-writer
https://github.com/yuchdev/code_generator/blob/master/tests/test_cpp_function_writer.py

**Comment by yuchdev** [comment]
I think it's fine, I approve the PR

**Pull request merged**
